### ISSUE TITLE
Use Python solution for colorizing output

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#10]
In [ratchet.py](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/ratchet.py#L26-L34) will include BASH color characters (aka ANSI color sequences), but we could just be using [colorama](https://pypi.python.org/pypi/colorama) or [termcolor](https://pypi.python.org/pypi/termcolor).

**Comment by amercer1** [comment]
ANSI color sequences have now been replaced by colorama!
