### ISSUE TITLE
Allow for verbose clank output showing task execution...

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#13]
Some of the tasks, when run in an continuous integration environment would benefit from showing the standard output of a actions a task is taking. 

It seems like we can keep the concise, nice output expected from playbooks and have an option to increase verbosity using [debug + when](http://docs.ansible.com/ansible/debug_module.html#examples):

```yaml
- tasks:
    - name: Run ls.sh and output "ls /"
      script: ls.sh
      register: out

    - debug: var=out.stdout_lines
      when: CLANK_VERBOSE 
```

source: [serverfault.com](http://serverfault.com/questions/537060/how-to-see-stdout-of-ansible-commands)

**Comment by amercer1** [comment]
Added verbose output for shell and command tasks that are conducted in clank. See commit [here](https://github.com/iPlantCollaborativeOpenSource/clank/compare/a75921b2b464...c2e320953ceb). To activate it, pass in the ```--verbose_output``` to ratchet.py. Feel free to comment on the change.
