### ISSUE TITLE
Disable and stop apache2/httpd before Nginx is started

### ISSUE THREAD

**Issue by nfaction** [iPlantCollaborativeOpenSource/clank#18]
Server halted on reboot due to both nginx and apache2 being bound to the same ports.  I manually stopped and disabled apache2, but it should be done via ansible before moving to nginx.

Might look something like this:
- name: stop apache before starting nginx to prevent port binding conflicts
  service: name=apache2 state=stopped enabled=no

**Comment by amercer1** [comment]
Fixed! Attempt to turn off apache before nginx is installed. Please see commit [here](https://github.com/iPlantCollaborativeOpenSource/clank/commit/6a5ec26172514fdcdcc24e57c9777fa99a1f88f9).

**Comment by amercer1** [comment]
Added this [commit](https://github.com/iPlantCollaborativeOpenSource/clank/commit/54db27179290121771f56acee443aa8a31a92ac8) just in case the install dependencies role is not ran and the others are.
