### ISSUE TITLE
add --tags support to include 'extra' deployment lines for vagrant

### ISSUE THREAD

**Issue by steve-gregory** [iPlantCollaborativeOpenSource/clank#21]
Current requirements:
- `--tags` support from ratchet (Ideally, using it instead of --skip-tags )
- add `vagrant` to 'the group(s)' that owns atmosphere/troposphere
- - www-data

More to come? maybe?

**Comment by amercer1** [comment]
- [ ] --tags
- [ ] vagrant

**Comment by amercer1** [comment]
Tags completed! Commit [here](https://github.com/iPlantCollaborativeOpenSource/clank/commit/52dcf2cbc5dc71a9dd358407070c5fb716399432)

**Comment by amercer1** [comment]
Vagrant completed! Commit [here](https://github.com/iPlantCollaborativeOpenSource/clank/commit/2ab8155e7b6e89c3f7d7ea710419d708b0065a60)
