### ISSUE TITLE
./clank.py needs less variables

### ISSUE THREAD

**Issue by steve-gregory** [iPlantCollaborativeOpenSource/clank#42]
Cutting down on the number of variables passed to `./clank.py`, both on the command line and in the `variables.yml` files, is essential to adoption.

We should use 'sensible' defaults wherever possible to avoid having to explicitly state every single variable.

**Comment by lenards** [comment]
We are preparing to shift `master` to `v2.0`. Although simplifications of variables was a major part of _v2.0_ design discussions, we have created substantial *value* with the pull requests against v2.0 and need to ensure those using the master (v1.0) release can benefit from it. 

This can be tackled in the first minor release of v2.0.

**Comment by amercer1** [comment]
This issue has been resolved.
