### ISSUE TITLE
Deal with uWSGI sockets

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#45]
Getting missing and permission issues with uWSGI sockets. Need to have clank create and modify permissions.

Error:
`connect() to unix:///tmp/troposphere.sock failed (2: No such file or directory) while connecting to upstream`

Notes for later.
http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

**Comment by lenards** [comment]
There is a permission mod in the template for the uWSGI ini files, you can see it here: 

https://github.com/iPlantCollaborativeOpenSource/troposphere/blob/master/extras/troposphere.uwsgi.ini.j2#L11-L13

It's likely just that the user is **not** in the group, but I believe that `www-data` had been working. 

The `LOCAL_DEV` here is how I change the permissions to be more permissive in a local environment, I do not think it is fully advisable in beta or prod. 

@steve-gregory - thoughts?

**Comment by steve-gregory** [comment]
@lenards Okay this is inline with our expectations - Thanks for the clarification, Based on the LoC in the link it looks like this issue has been resolved..

**Comment by amercer1** [comment]
False alarm! Just needed to restart atmosphere.
