### ISSUE TITLE
logrotate 

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#46]
Copy logrotate.atmosphere to `/etc/logrotate.d`

https://github.com/iPlantCollaborativeOpenSource/atmosphere/blob/master/extras/logrotate.atmosphere

**Comment by amercer1** [comment]
Copy logrotate.troposphere to /etc/logrotate.d

**Comment by lenards** [comment]
This is complete now, I think - right?

**Comment by amercer1** [comment]
This is now complete due to [PR](https://github.com/iPlantCollaborativeOpenSource/clank/pull/47).

💃
