### ISSUE TITLE
Npm builds fail and halts deployment process.

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#54]
Npm builds fail and halts deployment process. Possible fix is capture return code of npm build, and if it fails, nuke `rm -rf node_modules`. Then rebuild npm.

**Comment by lenards** [comment]
Got it 👍

**Comment by lenards** [comment]
If anyone wants to tackle this ... I'd just register an variable to determine the outcome of an npm install - then if it fails, `rm -rf node_modules` and re run the npm build.

**Comment by lenards** [comment]
If not - I will tackle this next week (I think it can wait)

**Comment by steve-gregory** [comment]
@amercer1 can take care of this with the infoz. Thanks @lenards

**Comment by lenards** [comment]
👍

**Comment by lenards** [comment]
Also, Andre sent me [this link](https://github.com/npm/npm/issues/11283) about how npm is slowed down by the progress-bar being active. We should consider disabling it and timing to see if there is a benefit since we can't see that visual feedback anyway.

**Comment by amercer1** [comment]
I will tackle this ASAP. I will also attempt to speed up node install speeds by taking a look at toggling off the load bar.

**Comment by amercer1** [comment]
This issue was resolved with PR [61](https://github.com/iPlantCollaborativeOpenSource/clank/pull/61). Node modules are deleted and rebuilt if the build fails, and there is a decrease in install time due to disabling the progress bar.
