### ISSUE TITLE
Multiple Host * entries in the ~/.ssh/config

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#56]
```
IdentityFile /opt/dev/atmosphere/extras/ssh/id_rsa
IdentityFile /root/.ssh/id_rsa

Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null
Host *
      StrictHostKeyChecking no
# BEGIN ANSIBLE MANAGED BLOCK
Host *
    IdentityFile /opt/dev/atmosphere/extras/ssh/id_rsa
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
# END ANSIBLE MANAGED BLOCK
```
Perhaps default to templating it, and have the ability toggle the template off

**Comment by nfaction** [comment]
Either building a better regex for `blockinfile` OR just template out this file with flag for to enable this action, which a backup of the original file.

**Comment by amercer1** [comment]
Issue should be resolved with PR [59](https://github.com/iPlantCollaborativeOpenSource/clank/pull/59).
