### ISSUE TITLE
Create playbook/role to back up files/sql dumps etc

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#62]
Prior to a deployment of clank, backing up of data must occur. Perhaps sent in a flag `--backup` and have `ratchet.py` run a separate playbook that runs out of band from the standard clank roles.

**Comment by cdosborn** [comment]
👌 perhaps it could be the same sort of thing as "troposphere", "dependencies", etc.

**Comment by amercer1** [comment]
@steve-gregory I am imagining we do this as separate playbook runs to ensure we don't accidentally bulldoze our files/sqldumps/atmosphere stack and then run clank against it the instance without realizing something went wrong.

I would like to code up a solution that looks like

```
./clank.py --backup <other potential arguments here>
./clank.py --env_file $ENV_FILE
```

Does this sound promising?

**Comment by lenards** [comment]
Pull request #98 defined a role, [app-backup-postgres](https://github.com/iPlantCollaborativeOpenSource/clank/tree/v2.0/roles/app-backup-postgres). This will do a "pg_dumpall" and a "pg_dump" per database. 

See the [README.md](https://github.com/iPlantCollaborativeOpenSource/clank/blob/v2.0/roles/app-backup-postgres/README.md) for more information.

**Comment by steve-gregory** [comment]
Playbooks and flags exist to do virtualenv creation and backup files+databases.
