### ISSUE TITLE
Creating ssh keys default error

### ISSUE THREAD

**Issue by amercer1** [iPlantCollaborativeOpenSource/clank#73]
When CREATE_SSH_KEYS: true and the id_rsa and id_rsa.pub paths are blank, clank errors out.

Investigate further.

**Comment by lenards** [comment]
There are two factors to this: nginx failure on start and celery _passive_ failure.

**Comment by lenards** [comment]
Just want to point out that this observed failure is distinct / different from #79.

**Comment by lenards** [comment]
I believe that my changed in #95 will resolve this issue.

**Comment by amercer1** [comment]
This issue has been in PR [95](https://github.com/iPlantCollaborativeOpenSource/clank/pull/95).
