### ISSUE TITLE
Clank v2.0 still installs transitive dependency `ruby1.9.1`

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#80]
In review `DEV_PACKAGES` for [`roles/install-dependencies`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/v2.0/roles/install-dependencies/vars/Ubuntu.yml#L42), I noticed that `ruby1.9.1` is still called out by name. We know from #63 that Ubuntu 16.04 does not have this package and this item with `DEV_PACKAGES` causes a failure.

Ideally, I need to determine why `ruby1.9.1` is in `DEV_PACKAGES`. I believe it is because ruby 1.9.* is a transitive dependency of another package.

**Comment by amercer1** [comment]
>  (likely, Redis - perhaps?).
I checked the redis documentation and it only has deps of gcc and libc.

**Comment by lenards** [comment]
@amercer1 - you are correct, I was _way_ off base. 

I dug into Crushbone a bit, and the introduction of `ruby1.9.1` was when troposphere's build scripts were added: 

https://github.com/iPlantCollaborativeOpenSource/crushbone/commit/e41b7f9993ae4950f80d2ca36b971746d637a157#diff-7e7df952512fecc65138ea081c773d20

This was likely because of the use of the Sass tool (which _was_ implemented in Ruby). We **now** use a nodejs translation/loader for converting Sass into valid CSS. 

The `ruby1.9.1` can be removed from `DEV_PACKAGES` outright - [terminate with extreme prejudice](https://www.youtube.com/watch?v=GjB8z0Bvi14).

**Comment by lenards** [comment]
Once deleted, we can close this.

**Comment by amercer1** [comment]
Removed ruby dependency in a commit which can be seen [here](https://github.com/iPlantCollaborativeOpenSource/clank/commit/6b1a552488c8d717a38c43bd9b0461c31e8c3ee4).

**Comment by amercer1** [comment]
💃
