### ISSUE TITLE
Only `.replace` for strings

### ISSUE THREAD

**Issue by lenards** [iPlantCollaborativeOpenSource/clank#90]
The human-readable log output is **awesome**. 

But it does generate a warning for boolean variables:
```
TASK [local-env-additions : debug] *********************************************
ok: [localhost] => {
    "msg": true
}
 [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (</home/vagrant/clank/callback_plugins/human_log.CallbackModule object at 0x7f96267e87d0>): 'bool' object
has no attribute 'replace'
```

This has to do with [human_log](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/callback_plugins/human_log.py#L37) always doing a replace on the field returned. I think what you want is to say ... if `output` is of type str - do a replace, other wise - just pass it on ... 

To recreate this ... 

In variables.yml
```
# ... 
VAGRANT: True
```

Then, in a roles or playbook:
```
---
- debug: msg="{{ VAGRANT }}"
```

**Comment by lenards** [comment]
I think that we just need to ensure that [`_format_output`](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/callback_plugins/human_log.py#L79-L81) returns a string which will guarantee there is a `replace` method to be called.

**Comment by amercer1** [comment]
This issue was resolved in PR [97](https://github.com/iPlantCollaborativeOpenSource/clank/pull/97).
