### ISSUE TITLE
More instructions or FAQ in README?

### ISSUE THREAD

**Issue by xuhang57** [iPlantCollaborativeOpenSource/clank#99]
So currently, we are re-configuring Atmosphere using clank in Ubuntu 14.04 LTS. 

After finishing configuring with `variables.yml` and passing all the tasks, I can only see the "successful installation" static page of Nginx in my host address. And Nginx gives me a `2016/07/26 15:28:58 [emerg] 24475#24475: no host in upstream "" in /etc/nginx/locations/lb.conf:2 error. 
` ( I doubled checked the `server-url` variable in the `variables.yml` is corrected and matched)

I am wondering which part goes wrong with the configuration process and once we figure out, could contribute with writing something like "Steps" or "FAQ" in the README file to make it detailed? 

Thanks for your help! I really appreciate it. Learned a lot of things 👍

**Comment by xuhang57** [comment]
I deleted `location ~^/api/(leaderboard|metrics) {
    proxy_pass http://;
}
` in the `lb.conf` and based on #79 , I think I fixed the Nginx problem. However, the host still showing Nginx page.

**Comment by lenards** [comment]
Lucas, if you have not been contacted yet - you might want to try using `v2.0`.

**Comment by xuhang57** [comment]
Thanks Lenard! I was using the other branch. It is now fixed. Thanks again 👍
